MINIMUM_PROFIT = 0.5 #In Percent
INPUT_LENGTH = 100
PREDICTION_LENGTH = 15


COMISSION = 2 
COMISSION_TYPE = "ABSOLUTE" #Either "ABSOLUTE" or "PERCENT"

CHECKPOINT_DIR = './training_checkpoints'
LOG_DIR ='./logs'
MODEL_FILE = 'trend_model.keras'